### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by pbobyn91** [KarimTahan/novel-generator-ui#1]
I am trying to create a Dockerfile for this project and I am getting this error:

(node:1) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/app/src/index.js:2
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

We will have to look into this to see what we can do. 

I will create a new branch called Dockerfile with my file in it when I am given access.

**Comment by pbobyn91** [comment]
This has been fixed
